# Get table from here -
# https://github.com/pixelsign/html5-device-mockups
# check for missing from here:
# https://github.com/pixelsign/html5-device-mockups/blob/master/src/scss/devices.scss

LANG_CHOICES = [
    ('', '-default-'),
    ('apollo', 'apollo'),
    ('basic', 'basic'),
    ('bsh', 'bsh'),
    ('c', 'c'),
    ('cc', 'cc'),
    ('clj', 'clj'),
    ('cpp', 'cpp'),
    ('cs', 'cs'),
    ('csh', 'csh'),
    ('css', 'css'),
    ('cv', 'cv'),
    ('cyc', 'cyc'),
    ('dart', 'dart'),
    ('erlang', 'erlang'),
    ('ex', 'ex'),
    ('go', 'go'),
    ('hs', 'hs'),
    ('htm', 'htm'),
    ('html', 'html'),
    ('java', 'java'),
    ('js', 'js'),
    ('kotlin', 'kotlin'),
    ('lasso', 'lasso'),
    ('lisp', 'lisp'),
    ('llvm', 'llvm'),
    ('logtalk', 'logtalk'),
    ('lua', 'lua'),
    ('m', 'm'),
    ('matlab', 'matlab'),
    ('ml', 'ml'),
    ('mumps', 'mumps'),
    ('mxml', 'mxml'),
    ('n', 'n'),
    ('pascal', 'pascal'),
    ('perl', 'perl'),
    ('pl', 'pl'),
    ('pm', 'pm'),
    ('proto', 'proto'),
    ('py', 'py'),
    ('r', 'r'),
    ('rb', 'rb'),
    ('rd', 'rd'),
    ('rust', 'rust'),
    ('scala', 'scala'),
    ('sh', 'sh'),
    ('sql', 'sql'),
    ('swift', 'swift'),
    ('tcl', 'tcl'),
    ('tex', 'tex'),
    ('vb', 'vb'),
    ('vhdl', 'vhdl'),
    ('wiki', 'wiki'),
    ('xhtml', 'xhtml'),
    ('xml', 'xml'),
    ('xq', 'xq'),
    ('xsl', 'xsl'),
    ('yaml', 'yaml'),
]

SKIN_CHOICES = [
    ('', 'default'),
    ('desert', 'desert'),
    ('sunburst', 'sunburst'),
    ('sons-of-obsidian', 'sons-of-obsidian'),
    ('doxy', 'doxy'),
]
