# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePrettify',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_code_prettify_codeprettify', serialize=False, to='cms.CMSPlugin')),
                ('lang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code Language')),
                ('skin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skin')),
                ('linenums', models.BooleanField(default=True, verbose_name='Line Numbers')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Code')),
                ('id_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID name')),
                ('additional_classes', models.CharField(blank=True, help_text='Additional comma separated list of classes to be added to the element e.g. "row, column-12, clearfix".', max_length=255, verbose_name='Additional classes')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
