# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_code_prettify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeprettify',
            name='start_linenum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Optional Start Line Number'),
        ),
    ]
