# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_code_prettify', '0002_codeprettify_start_linenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeprettify',
            name='start_linenum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Optional Start Line Number'),
        ),
    ]
