# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_code_prettify', '0003_auto_20190523_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeprettify',
            name='show_all_linenums',
            field=models.BooleanField(default=False, verbose_name='Show All Line Numbers'),
        ),
    ]
