# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_code_prettify', '0004_codeprettify_show_all_linenums'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeprettify',
            name='autorun',
            field=models.BooleanField(default=True, verbose_name='Run automatically on page load'),
        ),
    ]
